name: blockwars
version: '${project.version}'
main: de.silver.blockwars.Blockwars
api-version: '1.20'
load: STARTUP
commands:
  fly:
  gm:
  heal:
  workbench:
vanish:
  description: "Vanish a player."
  usage: "/vanish [player]"
  permission: Blockwars.vanish