name: blockwars
version: '1.0-SNAPSHOT'
main: de.silver.blockwars.Blockwars
api-version: '1.20'
load: STARTUP
commands:
  fly:
  gm:
  heal:
  workbench:
    aliases: wb
  vanish:
    aliases: v
  discord:
    aliases: dc
  enderchest:
    aliases: ec
  day:
  night: